config/routes.rb
Rails.application.routes.draw do
  resources :smsrequests
  resources :reservations
  root 'reservations#customer_view'
  get 'reservations/customer_view' => 'reservations#customer_view'
  get 'check_in' => 'reservations#check_in'
  post 'check_in_customer' => 'reservations#check_in_customer'
  post 'reservations/add_res' => 'reservations#add_res'
  put "/sendsms/:id" => 'reservations#send_text_message', as: 'send_text_message'

  get "/getsmslist" => 'smsrequests#getsmslist', as: 'getsmslist'

end

app/models/reservation.rb
class Reservation < ActiveRecord::Base
  VALID_PHONE_NUMBER_REGEX = /[0-9]{11}/x
  validates :mobile, presence: true, length: {maximum: 11}, format: { with: VALID_PHONE_NUMBER_REGEX,
    message: "only allow valid international phone numbers" }
end

app/controllers/reservations_controller.rb
require 'rest-client'
require 'json'

class ReservationsController < ApplicationController
  before_action :set_reservation, only: [:show, :edit, :update, :destroy, :display_reservation_details, :send_text_message]

  def check_in_customer
    redirect_to reservations_url
  end

  def get_received_messages

     

  end

  def send_reservation_sms

#      puts "***********   " + @reservation.mobile

      client = Textmagic::REST::Client.new 'benowen', 'UMVvGqt5y6ftjSx0FcGyzyBZJryPRG'

      mobile = "+44"+@reservation.mobile[1..-1]

      puts "***********    "+mobile

      params = {phones: mobile, text: 'Hello '+@reservation.customername+', Your reservation has been successful.'}

      sent_message = client.messages.create(params)

  end

  def send_text_message

    puts @reservation.mobile

 #   mobilenumber = @reservation.mobile

    client = Textmagic::REST::Client.new 'benowen', 'UMVvGqt5y6ftjSx0FcGyzyBZJryPRG'


    mobile = "+44"+@reservation.mobile[1..-1]

    # Send a text message
    # Any phone number that starts with 999 is a test phone number
    # The phones parameter can contain more than one number (comma delimited)
    params = {phones: mobile, text: 'Hello '+@reservation.customername+', The code for your room entry is '+@reservation.pinnumber+' please make a note of this. It will be valid 11am tomorrow'}

    # This next line creates and sends the message
    sent_message = client.messages.create(params)
    puts "The sent message id: #{sent_message.id}"
    puts "The sent message URL: #{sent_message.href}"
    puts ''

    # Read messages sent to your Textmagic account
    # By default, client.replies.list() fetches the last 10 messages you've received
    received_messages = client.replies.list()
    if received_messages.resources.length == 0
      puts 'We haven\'t received any SMS messages with our TextMagic account yet'
    else
       received_messages.resources.each do |rm|
          puts "The received message text: #{rm.text}"
          puts "The message was sent from: #{rm.sender}"
          puts ''
       end
    end
  end

  # GET /reservations
  # GET /reservations.json
  def index
    @reservations = Reservation.all
  end

  # GET /reservations/1
  # GET /reservations/1.json
  def show
  end

  # GET /reservations/customer_view
  def customer_view
    @reservation = Reservation.new
  end

  # GET /reservations/new
  def new
    @reservation = Reservation.new
  end

  # GET /reservations/1/edit
  def edit
  end

  def display_reservation_details 
    puts "Yo!"
    respond_to do |format|
      format.js
    end
  end

  def add_res


    

    @reservation = Reservation.new(reservation_params)
    @reservation.mobile = @reservation.mobile.gsub(/\s+/, "")
    @reservation.roomnumber = 200 + rand(299)
    @reservation.pinnumber = 1 + rand(9999)

    response_str = '{  "roomnumber": "'+@reservation.roomnumber+'", "pinnumber": "'+@reservation.pinnumber+'" }'

    update_data(response_str)
    puts "Phone Number " << @reservation.mobile
    send_reservation_sms

#    send_text_message

    respond_to do |format|
      if @reservation.save
        format.html { redirect_to check_in_url, notice: 'Reservation was successfully updated.' }
        format.json { render :display_reservation_details, status: :created, location: @reservation }
      else
        format.html { render :new }
        format.json { render json: @reservation.errors, status: :unprocessable_entity }
      end
    end
  end

  def update_data(response_str)

     response_json = JSON.parse(response_str)
     puts_response = RestClient.post("http://pricefighter.enablingdigital.co.uk/reservations.json",
         response_json.to_json,      # Re-encode the entire incident as JSON
         {:content_type => 'application/json'})
  end

  def check_in
    @reservation = Reservation.new

  end

  def check_in_customer
    @reservation = Reservation.where(customername: reservation_params[:customername]).first 
    if @reservation.nil?
      redirect_to check_in_path, notice: 'Reservation Not Found, please check reservation details.'
    else
      send_text_message
      render action: 'check_in_customer', notice: 'Reservation was Successfully Found.'
    end
  end

  # POST /reservations
  # POST /reservations.json
  def create
    @reservation = Reservation.new(reservation_params)

    respond_to do |format|
      if @reservation.save
        format.html { redirect_to @reservation, notice: 'Reservation was successfully created.' }
        format.json { render :show, status: :created, location: @reservation }
      else
        format.html { render :new }
        format.json { render json: @reservation.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /reservations/1
  # PATCH/PUT /reservations/1.json
  def update

    puts "*************** update"

    respond_to do |format|
      if @reservation.update(reservation_params)
        format.html { redirect_to @reservation, notice: 'Reservation was successfully updated.' }
        format.json { render :show, status: :ok, location: @reservation }
      else
        format.html { render :edit }
        format.json { render json: @reservation.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /reservations/1
  # DELETE /reservations/1.json
  def destroy
    @reservation.destroy
    respond_to do |format|
      format.html { redirect_to reservations_url, notice: 'Reservation was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_reservation
      @reservation = Reservation.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def reservation_params
      params.require(:reservation).permit(:customername, :location, :roomnumber, :startdatetime, :enddatetime, :pinnumber, :mobile, :cleanername, :roomtype)
    end
end

app/helpers/reservations_helper.rb
module ReservationsHelper
end

app/views/reservations/_check_in_form.html.erb
<%= form_for(@reservation, url: {action: "check_in_customer"}) do |f| %>
  <% if @reservation.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@reservation.errors.count, "error") %> prohibited this reservation from being saved:</h2>

      <ul>
      <% @reservation.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="col-xs-12" id="fieldgroup">
    <!-- <%= f.label :customername %><br> -->
    <%= f.text_field :customername, :placeholder => "Your first name", :id => "input1", :class => "form-control center-block" %>
  </div>
  <!-- <div class="col-xs-12" id="fieldgroup"> -->
    <!-- <%= f.label :mobile %><br> -->
    <!-- <%= f.text_field :mobile %> -->
  <!-- </div> -->
  <div class="col-xs-12" id="buttongroup">
    <%= f.submit "Check In", :id => "submitbutton", :class => "center-block" %>
  </div>
<% end %>

app/views/reservations/_customer_form.html.erb
<%= form_for(@reservation, url: {action: "add_res"}) do |f| %>
  <% if @reservation.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@reservation.errors.count, "error") %> prohibited this reservation from being saved:</h2>

      <ul>
      <% @reservation.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label "Customer Name" %><br>
    <%= f.text_field :customername %>
  </div>
  <div class="field">
    <%= f.label :location %><br>
    <%= f.select(:location, ['Paddington Pricefighter', 'Reading Pricefighter']) %>
  </div>
  <div class="field">
    <%= f.label "Start Date" %><br>
    <%= f.date_select :startdatetime %>
  </div>
  <div class="field">
    <%= f.label "End Date" %><br>
    <%= f.date_select :enddatetime %>
  </div>
  <div class="field">
    <%= f.label :mobile %><br>
    <%= f.text_field :mobile %>
  </div>
  <div class="field">
    <%= f.label :roomtype %><br>
    <%= f.select(:roomtype, ['Single','Double']) %>
  </div>
  <div id="reservation_id"></div>
  <div class="actions">
    <%= f.submit 'Request', :class => 'submit_id', :id => 'submit_id' %>
  </div>
<% end %>

app/views/reservations/_form.html.erb
<%= form_for(@reservation) do |f| %>
  <% if @reservation.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@reservation.errors.count, "error") %> prohibited this reservation from being saved:</h2>

      <ul>
      <% @reservation.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :customername %><br>
    <%= f.text_field :customername %>
  </div>
  <div class="field">
    <%= f.label :location %><br>
    <%= f.text_field :location %>
  </div>
  <div class="field">
    <%= f.label :roomnumber %><br>
    <%= f.text_field :roomnumber %>
  </div>
  <div class="field">
    <%= f.label :startdatetime %><br>
    <%= f.datetime_select :startdatetime %>
  </div>
  <div class="field">
    <%= f.label :enddatetime %><br>
    <%= f.datetime_select :enddatetime %>
  </div>
  <div class="field">
    <%= f.label :pinnumber %><br>
    <%= f.text_field :pinnumber %>
  </div>
  <div class="field">
    <%= f.label :mobile %><br>
    <%= f.text_field :mobile %>
  </div>
  <div class="field">
    <%= f.label :cleanername %><br>
    <%= f.text_field :cleanername %>
  </div>
  <div class="field">
    <%= f.label :roomtype %><br>
    <%= f.text_field :roomtype %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/reservations/check_in.html.erb
<div id="notice"><%= notice %></div>

<div class="checkinbackground" style="height: 700px;">
  <div class="container">
    <div class="row">
      <div class="col-xs-12" style="margin-top: 80px;">
        <h1 id="fontwhite">Check-in to your cabin</h1>
      </div>
    </div>
    <div>
      <%= render 'check_in_form' %>
    </div>
  </div>
</div>

<%= link_to 'Back', reservations_path %>

app/views/reservations/check_in_customer.html.erb
<!-- <p id="notice"><%= notice %></p> -->
<div class="checkinbackground checkedin1">
<div class="container">
  <div class="row">
    <div id="white" class="col-xs-12">
<h1 id="checkedintitle">You're checked in <i id="smiley" class="fa fa-smile-o" aria-hidden="true"></i></h1>

<h3 id="entry">Your room number: <%= @reservation.roomnumber %></h3>
<h3 id="entry">Your room's pin: <%= @reservation.pinnumber %></h3>

<div class="border2">
</div>

  <!-- <div id="topentry"> -->
    <strong>Your name:</strong>
    <%= @reservation.customername %>
  <!-- </div> -->

  <br />

  <strong>Location:</strong>
  <%= @reservation.location %>

  <br />

  <strong>Check in:</strong>
  <%= @reservation.startdatetime %>

  <br />

  <strong>Check out:</strong>
  <%= @reservation.enddatetime %>

  <br />

  <!-- <strong>Pinnumber:</strong>
  <%= @reservation.pinnumber %>

  <br /> -->

  <strong>Mobile:</strong>
  <%= @reservation.mobile %>

<!--
<p>
  <strong>Cleanername:</strong>
  <%= @reservation.cleanername %>
</p> -->

<br />

  <strong>Roomtype:</strong>
  <%= @reservation.roomtype %>

</div>
<div class="col-xs-12">
  <button id="submitbutton">Book breakfast</button>
</div>
</div>
</div>
</div>
<%= link_to 'Edit', edit_reservation_path(@reservation) %> |
<%= link_to 'Back', reservations_path %>

app/views/reservations/customer_view.html.erb
<h1>Request a new  Reservation</h1>

<%= render 'customer_form' %>

<%= link_to 'Back', reservations_path %>

app/views/reservations/display_reservation_details.js.erb
alert("displayed!!");

app/views/reservations/edit.html.erb
<h1>Editing Reservation</h1>

<%= render 'form' %>

<%= link_to 'Show', @reservation %> |
<%= link_to 'Back', reservations_path %>

app/views/reservations/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Reservations</h1>

<table class="table">
  <thead class="thead-inverse">
    <tr>
      <th>Customer Name</th>
      <th>Location</th>
      <th>Roomnumber</th>
      <th>Check in</th>
      <th>Check out</th>
      <th>Pinnumber</th>
      <th>Mobile</th>
      <th>Cleanername</th>
      <th>Roomtype</th>
      <th colspan="4"></th>
    </tr>
  </thead>

  <tbody>
    <% @reservations.each do |reservation| %>
      <tr>
        <td><%= reservation.customername %></td>
        <td><%= reservation.location %></td>
        <td><%= reservation.roomnumber %></td>
        <td><%= reservation.startdatetime %></td>
        <td><%= reservation.enddatetime %></td>
        <td><%= reservation.pinnumber %></td>
        <td><%= reservation.mobile %></td>
        <td><%= reservation.cleanername %></td>
        <td><%= reservation.roomtype %></td>
        <td><%= link_to 'Show', reservation, class: "btn btn-primary" %></td>
        <td><%= link_to 'Edit', edit_reservation_path(reservation), class: "btn btn-primary" %></td>
        <td><%= link_to 'Destroy', reservation, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-primary" %></td>
        <td><%=  button_to 'Resend SMS', send_text_message_path(reservation), method: :put, remote: true, class: "btn btn-primary" %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<br>

<%= link_to 'New Reservation', new_reservation_path, class: "btn btn-primary" %>

app/views/reservations/new.html.erb
<h1>New Reservation</h1>

<%= render 'form' %>

<%= link_to 'Back', reservations_path %>

app/views/reservations/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Customername:</strong>
  <%= @reservation.customername %>
</p>

<p>
  <strong>Location:</strong>
  <%= @reservation.location %>
</p>

<p>
  <strong>Roomnumber:</strong>
  <%= @reservation.roomnumber %>
</p>

<p>
  <strong>Startdatetime:</strong>
  <%= @reservation.startdatetime %>
</p>

<p>
  <strong>Enddatetime:</strong>
  <%= @reservation.enddatetime %>
</p>

<p>
  <strong>Pinnumber:</strong>
  <%= @reservation.pinnumber %>
</p>

<p>
  <strong>Mobile:</strong>
  <%= @reservation.mobile %>
</p>

<p>
  <strong>Cleanername:</strong>
  <%= @reservation.cleanername %>
</p>

<p>
  <strong>Roomtype:</strong>
  <%= @reservation.roomtype %>
</p>

<%= link_to 'Edit', edit_reservation_path(@reservation) %> |
<%= link_to 'Back', reservations_path %>