config/routes.rb
Rails.application.routes.draw do
  resources :smsrequests
  resources :reservations
  root 'reservations#customer_view'
  get 'reservations/customer_view' => 'reservations#customer_view'
  get 'check_in' => 'reservations#check_in'
  post 'check_in_customer' => 'reservations#check_in_customer'
  post 'reservations/add_res' => 'reservations#add_res'
  put "/sendsms/:id" => 'reservations#send_text_message', as: 'send_text_message'

  get "/getsmslist" => 'smsrequests#getsmslist', as: 'getsmslist'

end

app/models/smsrequest.rb
class Smsrequest < ActiveRecord::Base
end

app/controllers/smsrequests_controller.rb
class SmsrequestsController < ApplicationController
  before_action :set_smsrequest, only: [:show, :edit, :update, :destroy]

  def getsmslist

      @smsrequests = []

      client = Textmagic::REST::Client.new 'benowen', 'UMVvGqt5y6ftjSx0FcGyzyBZJryPRG'

      received_messages = client.replies.list()
      if received_messages.resources.length == 0
         puts 'We haven\'t received any SMS messages with our TextMagic account yet'
      else
         received_messages.resources.each do |rm|

           request = Smsrequest.new
           request.mobile = rm.sender
           request.message = rm.text
  
           @smsrequests.push(request)
           

           puts "The received message text: #{rm.text}"
           puts "The message was sent from: #{rm.sender}"
           puts ''
       end
    end

    

#      @smsrequests = Smsrequest.all



  end

  # GET /smsrequests
  # GET /smsrequests.json
  def index
    @smsrequests = Smsrequest.all
  end

  # GET /smsrequests/1
  # GET /smsrequests/1.json
  def show
  end

  # GET /smsrequests/new
  def new
    @smsrequest = Smsrequest.new
  end

  # GET /smsrequests/1/edit
  def edit
  end

  # POST /smsrequests
  # POST /smsrequests.json
  def create
    @smsrequest = Smsrequest.new(smsrequest_params)

    respond_to do |format|
      if @smsrequest.save
        format.html { redirect_to @smsrequest, notice: 'Smsrequest was successfully created.' }
        format.json { render :show, status: :created, location: @smsrequest }
      else
        format.html { render :new }
        format.json { render json: @smsrequest.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /smsrequests/1
  # PATCH/PUT /smsrequests/1.json
  def update
    respond_to do |format|
      if @smsrequest.update(smsrequest_params)
        format.html { redirect_to @smsrequest, notice: 'Smsrequest was successfully updated.' }
        format.json { render :show, status: :ok, location: @smsrequest }
      else
        format.html { render :edit }
        format.json { render json: @smsrequest.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /smsrequests/1
  # DELETE /smsrequests/1.json
  def destroy
    @smsrequest.destroy
    respond_to do |format|
      format.html { redirect_to smsrequests_url, notice: 'Smsrequest was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_smsrequest
      @smsrequest = Smsrequest.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def smsrequest_params
      params.require(:smsrequest).permit(:mobile, :message)
    end
end

app/helpers/smsrequests_helper.rb
module SmsrequestsHelper
end

app/views/smsrequests/_form.html.erb
<%= form_for(@smsrequest) do |f| %>
  <% if @smsrequest.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@smsrequest.errors.count, "error") %> prohibited this smsrequest from being saved:</h2>

      <ul>
      <% @smsrequest.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :mobile %><br>
    <%= f.text_field :mobile %>
  </div>
  <div class="field">
    <%= f.label :message %><br>
    <%= f.text_field :message %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/smsrequests/_getsmslist.erb
<div class="container">

   <div class="row">

     <div class="col-xs-12">

<table class="table">
  <thead class="thead-inverse">
    <tr>
      <th>Mobile</th>
      <th>Message</th>
      <th>Room Number</th>
    </tr>
  </thead>

  <tbody>
    <% @smsrequests.each do |smsrequest| %>
      <tr>
        <td><%= smsrequest.mobile %></td>
        <td><%= smsrequest.message %></td>
        <td>215</td>
      </tr>
    <% end %>
  </tbody>
</table>

</div>
</div>
</div>

app/views/smsrequests/edit.html.erb
<h1>Editing Smsrequest</h1>

<%= render 'form' %>

<%= link_to 'Show', @smsrequest %> |
<%= link_to 'Back', smsrequests_path %>

app/views/smsrequests/getsmslist.js.erb
<%= render partial: "smsrequests/getsmslist" %>

app/views/smsrequests/index.html.erb
<p id="notice"><%= notice %></p>

<div class="container">

   <div class="row">

     <div class="col-xs-12">

<h1>Listing Smsrequests</h1>

</div>
</div>
</div>

<div id="smsdata">
<%= render partial: "smsrequests/getsmslist" %>
</div>

<br>

app/views/smsrequests/new.html.erb
<h1>New Smsrequest</h1>

<%= render 'form' %>

<%= link_to 'Back', smsrequests_path %>

app/views/smsrequests/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Mobile:</strong>
  <%= @smsrequest.mobile %>
</p>

<p>
  <strong>Message:</strong>
  <%= @smsrequest.message %>
</p>

<%= link_to 'Edit', edit_smsrequest_path(@smsrequest) %> |
<%= link_to 'Back', smsrequests_path %>