config/routes.rb
Rails.application.routes.draw do
  resources :smsrequests
  resources :reservations
  root 'reservations#customer_view'
  get 'reservations/customer_view' => 'reservations#customer_view'
  get 'check_in' => 'reservations#check_in'
  post 'check_in_customer' => 'reservations#check_in_customer'
  post 'reservations/add_res' => 'reservations#add_res'
  put "/sendsms/:id" => 'reservations#send_text_message', as: 'send_text_message'

  get "/getsmslist" => 'smsrequests#getsmslist', as: 'getsmslist'

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Whitbread</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link href='https://fonts.googleapis.com/css?family=Martel+Sans:400,300,600' rel='stylesheet' type='text/css'>
  <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.6.3/css/font-awesome.min.css" rel="stylesheet" integrity="sha384-T8Gy5hrqNKT+hzMclPo118YTQO6cYprQmhrYwIiQ/3axmI1hQomh7Ud2hPOy8SP1" crossorigin="anonymous">
</head>
<body id="font">
      <nav id="navbar" class="navbar navbar-static-top navbar-light bg-inverse navbar-custom">
        <!-- <%= image_tag "whitbread.png", class: "some css class here" %> -->
        <div class="container">
          <div class="row">
            <div class="col-xs-12">
              <i class="fa fa-home fa-2x pull-xs-left" style="color: #FF585B; margin-top:6px;" aria-hidden="true"></i>
              <h3 class="pull-xs-left" style=" margin-left:7px ; margin-top:11px; color: #363636;  font-weight: 600;">AirCabin</h3>
            </div>
          </div>
          </div>
        </div>
      </nav>
      <div class="border"></div>
  <!-- <div class="container">
    <div class="row"> -->
      <!-- <div class="jumbotron big-banner">
          <h1 class="display-3"></h1>
      </div> -->
    <!-- </div>
  </div> -->


    <%= yield %>



<footer class="footer">
</footer>

<div class="container">
  <span class="text-muted"><%= link_to "Customer Online Reserve", root_path(@profile), class: "btn btn-primary" %> <%= link_to "Customer Onsite Check In", check_in_path, class: "btn btn-primary" %> <%= link_to "Front Desk View", reservations_path, class: "btn btn-primary" %> <%= link_to "Monitor SMS Requests", smsrequests_path, class: "btn btn-primary" %></span>
</div>

</body>
</html>